### ISSUE TITLE
Valeurs progressBars

### ISSUE THREAD

**Issue by ZackBNT** [vmercy/AP4B_TerraGenesis#18]
Lier la valeur du progressBar de chaque condition avec le pourcentage actuel.

**Comment by ha161** [comment]
Bien reçu, il faut que j'ajoute à la fin de chaque fonction qui modifie les paramètres une update de la progressBar de ce paramètre c'est ça ? Tu sais comment je peux le lier à ta progressBar sachant que je n'ai pas ta partie dans ma branche ?

**Comment by ZackBNT** [comment]
J'aurais besoin juste des variables contenant la valeur de chaque condition et qui se changent tout au long du jeu.

**Comment by ha161** [comment]
D'accord ce sont les attributs de Game : money ; atmosphere ; oxygen ; carbonDioxide ; biomass (ce sont des double)

**Comment by ZackBNT** [comment]
Pour l'attribut money oui, on a besoin juste de la valeur en double.
Pour les autres on doit avoir leurs équivalents en pourcentage.
Car par exemple pour chaque progressBar on définit son pourcentage "progressBar.setValue(30);"

**Comment by ha161** [comment]
Je comprends, ce sont des doubles mais leur valeur sont comprises entre 0 et 100 comme des pourcentages

**Comment by ha161** [comment]
Avec quel type primitif tu veux représenter les pourcentages sinon ? Ca peut se faire avec des doubles il suffit juste de vérifier que leur valeur ne dépasse jamais 100 (100%)

**Comment by ZackBNT** [comment]
Si leur valeur en double est comprise entre 0 et 100 donc c'est bon.

**Comment by ha161** [comment]
Super, ce sera le cas
