### ISSUE TITLE
Lier la création des Factories avec le paramètre Biomass

### ISSUE THREAD

**Issue by ha161** [vmercy/AP4B_TerraGenesis#20]
Lier la création d'une usine avec l'augmentation de la jauge biomasse.

Ajouter un attribut à Factory avec l'avancé en pourcentage de la jauge quand on crée une usine à l'image des animaux pour le dioxyde de carbone et les plantes pour l'oxygène

**Comment by vmercy** [comment]
Juste pour être sûr, on considère que toutes les usines créent de la biomasse ? En réalité ce serait le contraire, si nos usines permettent d'acquérir des matériaux de construction elles devraient plutôt consommer de la biomasse. Mais pour simplifier on peut se dire que toutes nos usines sont des usines de valorisation énergétique et qu'elles en créent au lieu d'en consommer...

**Comment by ha161** [comment]
Je vois ce que tu veux dire, si on simplifie ça revient à faire ce que j'ai écris plus haut et ça sera vite réglée

**Comment by ha161** [comment]
Tu peux me donner le nom de l'attribut de Factory qui contient l'avancé en biomasse qu'ajoute une usine pour que j'écrive la fonction qui fait avancer la jauge stp

**Comment by vmercy** [comment]
c'est biomassGain. J'ai updaté l'UML (sur master) pour ajouter la classe Factory.

**Comment by ha161** [comment]
D'accord

**Comment by vmercy** [comment]
Fonctionne grâce aux nouvelles classes ConditionEvolution et ConditionsEvolution (voir UML)
