### ISSUE TITLE
Problème de package avec VSCode

### ISSUE THREAD

**Issue by vmercy** [vmercy/AP4B_TerraGenesis#21]
Sur VSCode, tous les fichiers d'un même package doivent se trouver dans un même dossier du nom du package, lui-même dans un dossier du nom du package. 
Je ne sais pas encore d'où vient le problème, mais pour pouvoir lancer le programme je suis obligé de tout déplacer dans des sous-dossiers de nom identifque.
Ex. : pour le package game, tous les fichiers doivent se trouver dans src/game/game pour que le programme puisse se lancer.

Je pense que je suis le seul du groupe concerné par le problème...
Ducoup ne soyez pas surpris si de telles structures de fichiers sont utilisées dans mes packages...

**Comment by ha161** [comment]
Entendu, ça va pauser problème quand on va merge les branches ?

**Comment by vmercy** [comment]
> Entendu, ça va pauser problème quand on va merge les branches ?

De votre côté non, du mien oui mais je ferai les modifs en conséquence. En gros si ça marche chez vous (ce qui sera déjà super bien !) il y a des risques que ça ne marche pas chez moi, mais tout ce qui marche chez moi marche aussi chez vous.
